name: Python Install & GitHub Models

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  models: read

jobs:
  install:
    name: Install Python dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - run: echo "::notice::✅ Python dependencies installed successfully!"

  # add one step here to call the GitHub Models action to download a model
  call-model:
    runs-on: ubuntu-latest
    name: Call GitHub model
    steps:
      - name: generate text using GitHub Models
        id: generate_text
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl "https://models.github.ai/inference/chat/completions" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -d '{
              "messages": [
                  {
                     "role": "user",
                     "content": "Explain the steps to create workflow files in GitHub Actions."
                  }
               ],
               "model": "openai/gpt-4o"
            }')
          echo "raw_reponse=$response" >> $GITHUB_OUTPUT

      - name: display AI response
        run: echo "::notice::✅ GitHub Model called successfully!"
             echo "${{ steps.generate_text.outputs.raw_reponse }}"
 